services:
  #
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    hostname: 'neo4j'
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
    volumes:
      - ./volumes/neo4j_db/data:/data
      - ./volumes/neo4j_db/logs:/logs
      - ./volumes/neo4j_db/plugins:/plugins

      # Location where Database Dump files are stored. Also loaded from here.
      - ./volumes/neo4j_import:/var/lib/neo4j/import

  # Message Queue used to send send & distrubte drill jobs to driller-workers
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
     - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
     - ./volumes/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      # Pings rabbitmq service to check if started
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 5

  driller-worker:
    build: 
      context: ./
      dockerfile: ./driller/Dockerfile
    env_file: .env
    volumes:
     - ./driller/:/app/driller/  # For Development
     - ./common/:/app/common/    # For Development

     - ./volumes/repos:/app/repositories # Location of Repos to Drill/Where they will be cloned.
    deploy:
      replicas: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
      neo4j:
        condition: service_started

  backend:
    container_name: backend
    ports:
      - 8000:8000
    build: 
      context: ./
      dockerfile: ./backend/Dockerfile
    env_file: .env
    network_mode: host
    volumes:
     - ./backend/:/app/backend/ # For Development
     - ./common/:/app/common/ # For Development

     - ./volumes/queries:/app/backend/queries # Location of Cypher Queries
     - ./volumes/configs:/app/backend/configs # Location of Drill Config Files
     - ./volumes/neo4j_import/:/app/neo4j_import/
    depends_on:
      neo4j:
        condition: service_started
      driller-worker:
        condition: service_started

  frontend:
    container_name: frontend
    ports:
      - 5173:5173
    build: 
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/:/app/frontend/
      - ./schemas/:/app/schemas/
    depends_on:
      - backend
    
