[tool.poetry]
name = "driller"
version = "0.1.0"
description = ""
authors = ["Andrew Rutherfoord <andrew.rutherfoord@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
common = { path = "../common"}
pika = "^1.3.2"
graphrepo = { version = "^0.4.0", source = "pypi-priv" }

[[tool.poetry.source]]
name = "pypi-priv"
url = "http://10.10.1.4:8083/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
driller-worker = "driller.main:main"
test-client = "driller.test_client:main"
