"""Added Job Status message field

Revision ID: c60111c8977d
Revises: 9f9a6f0e5ac2
Create Date: 2024-06-24 17:01:38.055103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision: str = 'c60111c8977d'
down_revision: Union[str, None] = '9f9a6f0e5ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobstatus', sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobstatus', 'message')
    # ### end Alembic commands ###
