neo:
  db_url: localhost
  port: 7687
  db_user: neo4j
  db_pwd: neo4j123
  batch_size: 50

repositories:
  defaults:
    start_date: 1 April, 2022 00:00
    end_date: 30 June, 2022 00:00
    index_code: False
    index_developer_email: True
  projects:
    - project_id: 'pydriller'
      url: https://github.com/ishepard/pydriller.git
      repo: pydriller
      start_date: 1 April, 2019 00:00
      end_date: 30 April, 2022 00:00
