
defaults:
  delete_clone: false

repositories:
  - name: 'pydriller'
    url: https://github.com/ishepard/pydriller.git
    index_file_modifications: False
    pydriller:
      since: <A Date string>
      from_commit: <some str>
      from_tag: <some str>
      to: <A Date string>
      to_commit: <some str>
      to_tag: <some str>
      only_in_branch: <some str>
      only_no_merge: <bool>
      only_authors: <list>
      only_commits: <list>
      only_release: <bool>
      filepath: <some filepath>
      only_modifications_with_file_types: <list>


    filters:
      commit:
        field: 'msg'
        filter_value: 'Update'
        method: 'exact' # can be exact, !exact, contains !contains
