repositories:
  defaults:
    end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    start_date: 1 April, 2019 00:00
  projects:
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: website-infrastructure
    repo: website-infrastructure
    start_date: 1 April, 2019 00:00
    url: https://github.com/InvictrixRom/website-infrastructure.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: bespin
    repo: bespin
    start_date: 1 April, 2019 00:00
    url: https://github.com/schramm-famm/bespin.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform
    repo: terraform
    start_date: 1 April, 2019 00:00
    url: https://github.com/Xin00163/terraform.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: quickstart
    repo: quickstart
    start_date: 1 April, 2019 00:00
    url: https://github.com/rancher/quickstart.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: prometheus-aws-configuration-beta
    repo: prometheus-aws-configuration-beta
    start_date: 1 April, 2019 00:00
    url: https://github.com/alphagov/prometheus-aws-configuration-beta.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: parkrunpointsleague
    repo: parkrunpointsleague
    start_date: 1 April, 2019 00:00
    url: https://github.com/davidcallen/parkrunpointsleague.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: mp-infrastructure
    repo: mp-infrastructure
    start_date: 1 April, 2019 00:00
    url: https://github.com/IoT-Data-Marketplace/mp-infrastructure.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-aws-modules
    repo: terraform-aws-modules
    start_date: 1 April, 2019 00:00
    url: https://github.com/deptno/terraform-aws-modules.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-for-beginners
    repo: terraform-for-beginners
    start_date: 1 April, 2019 00:00
    url: https://github.com/bretmullinix/terraform-for-beginners.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: vof-deployment-scripts
    repo: vof-deployment-scripts
    start_date: 1 April, 2019 00:00
    url: https://github.com/scott45/vof-deployment-scripts.git
