neo:
  db_url: neo4j
  port: 7687
  db_user: neo4j
  db_pwd: neo4j123
  batch_size: 50
  
repositories:
  defaults: 
    start_date: 1 April, 2022 00:00
    end_date: 30 June, 2022 00:00
  projects:
  - index_code: false
    project_id: website-infrastructure
    repo: website-infrastructure
    url: https://github.com/InvictrixRom/website-infrastructure.git
  - index_code: false
    project_id: bespin
    repo: bespin
    url: https://github.com/schramm-famm/bespin.git