repositories:
  defaults:
    end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    start_date: 1 April, 2019 00:00
  projects:
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: website-infrastructure
    repo: website-infrastructure
    start_date: 1 April, 2019 00:00
    url: https://github.com/InvictrixRom/website-infrastructure.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: bespin
    repo: bespin
    start_date: 1 April, 2019 00:00
    url: https://github.com/schramm-famm/bespin.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform
    repo: terraform
    start_date: 1 April, 2019 00:00
    url: https://github.com/Xin00163/terraform.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: quickstart
    repo: quickstart
    start_date: 1 April, 2019 00:00
    url: https://github.com/rancher/quickstart.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: prometheus-aws-configuration-beta
    repo: prometheus-aws-configuration-beta
    start_date: 1 April, 2019 00:00
    url: https://github.com/alphagov/prometheus-aws-configuration-beta.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: parkrunpointsleague
    repo: parkrunpointsleague
    start_date: 1 April, 2019 00:00
    url: https://github.com/davidcallen/parkrunpointsleague.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: mp-infrastructure
    repo: mp-infrastructure
    start_date: 1 April, 2019 00:00
    url: https://github.com/IoT-Data-Marketplace/mp-infrastructure.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-aws-modules
    repo: terraform-aws-modules
    start_date: 1 April, 2019 00:00
    url: https://github.com/deptno/terraform-aws-modules.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-for-beginners
    repo: terraform-for-beginners
    start_date: 1 April, 2019 00:00
    url: https://github.com/bretmullinix/terraform-for-beginners.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: vof-deployment-scripts
    repo: vof-deployment-scripts
    start_date: 1 April, 2019 00:00
    url: https://github.com/scott45/vof-deployment-scripts.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: Azure-Terraform-Budget
    repo: Azure-Terraform-Budget
    start_date: 1 April, 2019 00:00
    url: https://github.com/Pavel-Hrabec/Azure-Terraform-Budget.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-google-vault
    repo: terraform-google-vault
    start_date: 1 April, 2019 00:00
    url: https://github.com/terraform-google-modules/terraform-google-vault.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: infra
    repo: infra
    start_date: 1 April, 2019 00:00
    url: https://github.com/mdn/infra.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-logs-module
    repo: terraform-logs-module
    start_date: 1 April, 2019 00:00
    url: https://github.com/willfarrell/terraform-logs-module.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-gcp-audit-log
    repo: terraform-gcp-audit-log
    start_date: 1 April, 2019 00:00
    url: https://github.com/lacework/terraform-gcp-audit-log.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-eks
    repo: terraform-eks
    start_date: 1 April, 2019 00:00
    url: https://github.com/eduardobaitello/terraform-eks.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: hmpps-env-configs
    repo: hmpps-env-configs
    start_date: 1 April, 2019 00:00
    url: https://github.com/ministryofjustice/hmpps-env-configs.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: jt-aws-serverless-app
    repo: jt-aws-serverless-app
    start_date: 1 April, 2019 00:00
    url: https://github.com/vuvuzella/jt-aws-serverless-app.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-google-nat-gateway
    repo: terraform-google-nat-gateway
    start_date: 1 April, 2019 00:00
    url: https://github.com/GoogleCloudPlatform/terraform-google-nat-gateway.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: viya4-iac-gcp
    repo: viya4-iac-gcp
    start_date: 1 April, 2019 00:00
    url: https://github.com/sassoftware/viya4-iac-gcp.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: TerraformTutorial
    repo: TerraformTutorial
    start_date: 1 April, 2019 00:00
    url: https://github.com/Arkoprabho/TerraformTutorial.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-ec2-gitlab-runner
    repo: terraform-ec2-gitlab-runner
    start_date: 1 April, 2019 00:00
    url: https://github.com/naciriii/terraform-ec2-gitlab-runner.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-aws-mcaf-matillion
    repo: terraform-aws-mcaf-matillion
    start_date: 1 April, 2019 00:00
    url: https://github.com/schubergphilis/terraform-aws-mcaf-matillion.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terralab
    repo: terralab
    start_date: 1 April, 2019 00:00
    url: https://github.com/gstimac/terralab.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-azure-kubernetes
    repo: terraform-azure-kubernetes
    start_date: 1 April, 2019 00:00
    url: https://github.com/poseidon/terraform-azure-kubernetes.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: fogg-env
    repo: fogg-env
    start_date: 1 April, 2019 00:00
    url: https://github.com/imma/fogg-env.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: projectQuickStart
    repo: projectQuickStart
    start_date: 1 April, 2019 00:00
    url: https://github.com/barloes/projectQuickStart.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: academeez-iac
    repo: academeez-iac
    start_date: 1 April, 2019 00:00
    url: https://github.com/ywarezk/academeez-iac.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: clouduru-infra
    repo: clouduru-infra
    start_date: 1 April, 2019 00:00
    url: https://github.com/andreishappy/clouduru-infra.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: tdr-grafana
    repo: tdr-grafana
    start_date: 1 April, 2019 00:00
    url: https://github.com/nationalarchives/tdr-grafana.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: dcp-monitoring
    repo: dcp-monitoring
    start_date: 1 April, 2019 00:00
    url: https://github.com/HumanCellAtlas/dcp-monitoring.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: sap-automation
    repo: sap-automation
    start_date: 1 April, 2019 00:00
    url: https://github.com/Azure/sap-automation.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: parking-status
    repo: parking-status
    start_date: 1 April, 2019 00:00
    url: https://github.com/itzik-bd/parking-status.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: seed-node-fallback-domain-config
    repo: seed-node-fallback-domain-config
    start_date: 1 April, 2019 00:00
    url: https://github.com/RavenProject/seed-node-fallback-domain-config.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: cool-sharedservices-nessus
    repo: cool-sharedservices-nessus
    start_date: 1 April, 2019 00:00
    url: https://github.com/cisagov/cool-sharedservices-nessus.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: grok-airflow
    repo: grok-airflow
    start_date: 1 April, 2019 00:00
    url: https://github.com/JaredStufftGD/grok-airflow.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-module-azure-datalake
    repo: terraform-module-azure-datalake
    start_date: 1 April, 2019 00:00
    url: https://github.com/datarootsio/terraform-module-azure-datalake.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: cloudblock
    repo: cloudblock
    start_date: 1 April, 2019 00:00
    url: https://github.com/chadgeary/cloudblock.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: waapdemo
    repo: waapdemo
    start_date: 1 April, 2019 00:00
    url: https://github.com/dankline/waapdemo.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: aws-crawler
    repo: aws-crawler
    start_date: 1 April, 2019 00:00
    url: https://github.com/andyfangdz/aws-crawler.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: tripstagger-google-infrastructure
    repo: tripstagger-google-infrastructure
    start_date: 1 April, 2019 00:00
    url: https://github.com/Tripstagger-AA/tripstagger-google-infrastructure.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: iks_vpc_lab
    repo: iks_vpc_lab
    start_date: 1 April, 2019 00:00
    url: https://github.com/ibm-cloud-architecture/iks_vpc_lab.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: eng-ci
    repo: eng-ci
    start_date: 1 April, 2019 00:00
    url: https://github.com/plxis/eng-ci.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-modules
    repo: terraform-modules
    start_date: 1 April, 2019 00:00
    url: https://github.com/XenitAB/terraform-modules.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: micro-service-as-code
    repo: micro-service-as-code
    start_date: 1 April, 2019 00:00
    url: https://github.com/GBergeret/micro-service-as-code.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: cloud-platform-terraform-monitoring
    repo: cloud-platform-terraform-monitoring
    start_date: 1 April, 2019 00:00
    url: https://github.com/ministryofjustice/cloud-platform-terraform-monitoring.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-docker-swarm
    repo: terraform-docker-swarm
    start_date: 1 April, 2019 00:00
    url: https://github.com/lancekuo/terraform-docker-swarm.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: hush-house
    repo: hush-house
    start_date: 1 April, 2019 00:00
    url: https://github.com/concourse/hush-house.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: terraform-azurerm-vmseries-modules
    repo: terraform-azurerm-vmseries-modules
    start_date: 1 April, 2019 00:00
    url: https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules.git
  - end_date: 20 April, 2024 00:00
    index_code: false
    index_developer_email: true
    project_id: s3-bucket-versioning
    repo: s3-bucket-versioning
    start_date: 1 April, 2019 00:00
    url: https://github.com/chqaversion/s3-bucket-versioning.git
